version: '3.8'

services:
  blog-app:
    image: devonwilkening/blog-server:latest
    container_name: my-blog-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    ports:
      - "3000:3000"  # Expose port 3000

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    restart: always  # Restart policy
    command: --cleanup --interval 30 my-blog-app  # Configure Watchtower
