name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install

      - name: Start Backend Server
        run: |
          cd backend
          npm run migrate  # Run database migrations
          npm start &  # Start the backend in the background

      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &  # Start frontend in the background
          sleep 15  # Wait for servers to start

      - name: Run Cypress E2E Tests
        run: |
          npx cypress run
          
      - name: Reset Database
        run: |
          cd backend
          npm run db:reset  # Example: Drop and recreate the database
